### ISSUE TITLE
Add option to remove product from library

### ISSUE THREAD

**Issue by fergus-macdubh** [fergus-macdubh/mermaid#101]
We need to have option to remove product from the library at all. If quantity of that product is not zero, then restrict deleting and show warning message.
Product shouldn't be completely removed from database, because it can have relations to completed orders. So, we need to add column and then filter by this column everywhere list of products are shown.

**Comment by AlesiaPavliuchenkova** [comment]
@fergus-macdubh , 
1. Should the button "Удалить" be added on "Склад" screen? 
2. We probably can enable it only when the quantity of product equals to zero otherwise it will be disabled.
Location of the button example:
![snip20180412_6](https://user-images.githubusercontent.com/11329105/38666218-1679c43c-3e47-11e8-894c-83632386c293.png)
.

**Comment by fergus-macdubh** [comment]
@AlesiaPavliuchenkova yes, seems good for me.

**Comment by AlesiaPavliuchenkova** [comment]
@fergus-macdubh ,
On storage screen we can see products with quantity greater than 0. (according to this logic there is no need to add "Delete" button), but there can be products with below quantity for example:
![snip20180412_8](https://user-images.githubusercontent.com/11329105/38680277-93d6633c-3e6e-11e8-8bdc-d1621cc5d9d7.png)
And such quantity on Storage screen will be shown as "0". 
Are we adding delete product option for such cases or may be there is some bug in saving product quantity that should be fixed? Because there are products in database with the strange quantity:
![snip20180412_9](https://user-images.githubusercontent.com/11329105/38680735-af9fa1a4-3e6f-11e8-9d4a-a1ea7e0b959a.png)
